"""Public API for the shared rhyme protocol."""
from .rhyme_protocol import (
    DEFAULT_EQUIVALENCE_PROFILE,
    DEFAULT_EQUIVALENCES,
    DEFAULT_MULTIGRAPHS,
    EQUIVALENCE_GROUPS,
    ProtocolConfig,
    RhymeMatch,
    RhymeProtocolError,
    RhymeSignature,
    available_equivalence_profiles,
    compare_rhyme_signatures,
    compare_words,
    equivalence_map_for_profile,
    extract_rhyme_signature,
    normalize_profile_name,
    rhyme_key,
    segment_word,
    words_rhyme,
)

__all__ = [
    "DEFAULT_EQUIVALENCE_PROFILE",
    "DEFAULT_EQUIVALENCES",
    "DEFAULT_MULTIGRAPHS",
    "EQUIVALENCE_GROUPS",
    "ProtocolConfig",
    "RhymeMatch",
    "RhymeProtocolError",
    "RhymeSignature",
    "available_equivalence_profiles",
    "compare_rhyme_signatures",
    "compare_words",
    "equivalence_map_for_profile",
    "extract_rhyme_signature",
    "normalize_profile_name",
    "rhyme_key",
    "segment_word",
    "words_rhyme",
]
